global:
  scrape_interval: 5s
scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - prometheus:9090
    labels:
      application: 'prometheus'
- job_name: payments
  metrics_path: /metrics
  static_configs:
  - targets:
    - pushgateway:9091
    - redis-exporter:9121
    - transaction-rest:8080
    labels: 
      application: 'payments'
