name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
         go-version: 1.23

    - name: Docker Compose Build
      run: docker compose build test-postgres-payments redis-payments payment-transaction-processor payment-transaction-rest

    - name: Docker Compose Up
      run: docker compose up test-postgres-payments redis-payments payment-transaction-processor payment-transaction-rest -d --wait

    - name: Install dependencies
      working-directory: ./payments-api
      run: go mod download

    - name: Test Unit
      working-directory: ./payments-api
      run: docker compose exec -e ENV=test  payment-transaction-rest go test -v -count=1 ./internal/adapter/repository/gormRepos ./internal/adapter/repository/redisRepos ./internal/core/service

    - name: Test Integration
      working-directory: ./payments-api
      run: docker compose exec -e ENV=test  payment-transaction-rest go test -v -count=1 ./internal/adapter/http/router
